# Generated by Django 3.0.7 on 2020-06-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0003_controlledhotspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledHotSpot1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publishTime', models.CharField(max_length=255)),
                ('repost', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('approve', models.IntegerField()),
                ('address', models.URLField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
